import json
import logging
from typing import Any, Dict, Union
from pydantic import ValidationError
from app.bob.schemas import BobReportOutput

logger = logging.getLogger(__name__)

class BobValidationError(Exception):
    """Raised when an IBM Bob response fails schema validation."""
    def __init__(self, message: str, raw_response: Any = None, validation_errors: Any = None):
        super().__init__(message)
        self.raw_response = raw_response
        self.validation_errors = validation_errors

class ReportValidator:
    """
    Validates, parses, and normalizes the forensic report generated by IBM Bob.
    Ensures zero hallucinated schema deviations and strict field types.
    """

    @classmethod
    def parse_and_validate(cls, raw: Union[str, Dict[str, Any]]) -> BobReportOutput:
        """
        Parses raw text or dictionary into a validated BobReportOutput.
        Handles markdown code-fence encapsulation (```json ... ```) or LLM chat wraps.
        """
        data = raw

        # If string, clean and parse JSON
        if isinstance(raw, str):
            cleaned = raw.strip()
            # Strip markdown json code block if present
            if cleaned.startswith("```"):
                lines = cleaned.splitlines()
                if lines[0].startswith("```"):
                    lines = lines[1:]
                if lines and lines[-1].strip() == "```":
                    lines = lines[:-1]
                cleaned = "\n".join(lines).strip()

            try:
                data = json.loads(cleaned)
            except json.JSONDecodeError as e:
                raise BobValidationError(
                    f"IBM Bob returned non-JSON string response: {str(e)}",
                    raw_response=raw
                ) from e

        if not isinstance(data, dict):
            raise BobValidationError(
                f"IBM Bob response root must be a JSON object, got {type(data).__name__}",
                raw_response=data
            )

        # Handle nested LLM response formats (e.g. OpenAI/IBM Bob format)
        if "choices" in data and isinstance(data["choices"], list) and len(data["choices"]) > 0:
            msg = data["choices"][0].get("message", {})
            content = msg.get("content", "")
            return cls.parse_and_validate(content)

        if "report" in data and isinstance(data["report"], dict):
            data = data["report"]

        # Validate against Pydantic schema
        try:
            validated = BobReportOutput.model_validate(data)
            return validated
        except ValidationError as err:
            err_details = err.errors()
            missing_fields = [e["loc"][0] for e in err_details if e.get("type") == "missing"]
            raise BobValidationError(
                f"IBM Bob response failed schema validation. Missing or invalid fields: {missing_fields}",
                raw_response=data,
                validation_errors=err_details
            ) from err

    @classmethod
    def build_correction_prompt(cls, validation_error: BobValidationError) -> str:
        """
        Constructs a targeted prompt for a 1-time corrective retry if Bob's first response was malformed.
        """
        errors_str = str(validation_error.validation_errors or validation_error)
        return (
            "CRITICAL: Your previous response failed forensic schema validation.\n"
            f"Validation Errors: {errors_str}\n\n"
            "You MUST respond ONLY with valid JSON conforming strictly to the requested schema. "
            "Do not include any conversational preamble or postscript."
        )
